prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

grafana:
  adminPassword: admin
  persistence:
    enabled: true
    size: 10Gi
  dashboards:
    default:
      email-validator-dashboard:
        file: dashboards/email-validator.json
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server
          access: proxy
          isDefault: true

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
        - match:
            severity: critical
          receiver: 'email'
    receivers:
      - name: 'null'
      - name: 'email'
        email_configs:
          - to: 'alert@yourdomain.com'
            from: 'alertmanager@yourdomain.com'
            smarthost: 'smtp.yourdomain.com:587'