apiVersion: v1
kind: Secret
metadata:
  name: email-validator-secrets
type: Opaque
stringData:
  database-url: postgresql://user:password@db:5432/emailvalidator
  redis-url: redis://redis:6379/0
  api-key: your-secure-api-key-here
  smtp-password: your-smtp-password
  aws-access-key: your-aws-access-key
  aws-secret-key: your-aws-secret-key