apiVersion: v1
kind: ConfigMap
metadata:
  name: email-validator-config
data:
  prometheus-config.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'email-validator'
        static_configs:
          - targets: ['localhost:8000']
  
  api-config.yml: |
    rate_limits:
      default: 100
      authenticated: 1000
    smtp:
      pool_size: 10
      connection_timeout: 30
      max_retries: 3
    monitoring:
      health_check_interval: 300
      metrics_port: 8000